### ISSUE TITLE
Support onion service statistics

### ISSUE THREAD

**Issue by robgjansen** [privcount/privcount#10]
Including but not limited to the following
- hidden service addresses (#336, #337, #338)
- descriptor uploads (#336)
- descriptor fetches on an HSDir (#337)
- establishments and introductions on an introduction point (#342, #343)
- successful and failed rendezvous (#344)
- circuit lifetime for rendezvous circuits (#344)
- data quantities on a rendezvous point (#344)

**Comment by teor2345** [comment]
It would be great if we could measure the actual lifetime of introduction point and rendezvous circuits, and failures in HSDir fetches, intro point and rendezvous circuit setups.

This has been requested by @dgoulet and https://trac.torproject.org/projects/tor/ticket/20082#comment:21

**Comment by teor2345** [comment]
Closing this, see the cross-references above for the tickets it was split into.
