### ISSUE TITLE
What is the minimum delay when the noise values change?

### ISSUE THREAD

**Issue by teor2345** [privcount/privcount#136]
Currently the minimum is the length of the previous collection period. Is this what you wanted, @ajohnson-nrl?

**Comment by ajohnson-nrl** [comment]
Not quite, @teor2345. The length of that delay is independent of the length of any collection period. It is an external value that affects privacy in that the differential-privacy guarantee is only provided to user activity that spans a period less than the delay. We suggest 24 hours as the length of that delay.

**Comment by teor2345** [comment]
So should there be a minimum on the delay at all?

Here's one design:
* We can default to min(24 hours, collection period).
* And we can make the absolute minimum min(10 minutes, collection period).

**Comment by ajohnson-nrl** [comment]
The delay should be completely independent of the length of the collection. So regardless of if it's a 10-minute collection or a 10-week collection, the k-hour delay is both necessary and sufficient to provide security to user activity contained within k hours. We should allow k to be configurable, and maybe provide a default of k = 24 hours.

**Comment by teor2345** [comment]
Ok, I understand.

I can imagine setting the default to 24 hours being problematic for short collections from a practical point of view. (Rather than anything to do with privacy of user activity).

Do we ever plan to do collections shorter than 24 hours?

**Comment by ajohnson-nrl** [comment]
Think of the delay like the epsilon and delta parameters. If a user wants to reduce their privacy protections to get accurate data in the short-term, then they can configure it to do so.

**Comment by teor2345** [comment]
Pull request #145 has a fix for this issue, it also fixes an issue in nearby code #144.
