### ISSUE TITLE
PrivCount expects an unauthenticated tor control port

### ISSUE THREAD

**Issue by teor2345** [privcount/privcount#140]
It's really important for security that we either teach PrivCount how to use the control socket (#134) or teach it how to authenticate using one of the secure authentication methods.

Otherwise, any local process owned by any user can reconfigure all the tor instances on the machine.

I think the control socket would be easier, but I'm not sure.

**Comment by teor2345** [comment]
@robgjansen do you want this in 0.2.0 or 0.3.0?
Maybe it depends on whether it's ready when your traffic modelling code is ready?

**Comment by robgjansen** [comment]
It won't affect my data collectors since I am the only one with access to those relays (with the assumption that my machines are not compromised). That being said, if we can get it done before #19 then that would be great, otherwise I'm OK with pushing it back to v0.3.0.

**Comment by teor2345** [comment]
This might be better implemented by porting PrivCount to use stem.
It would make it much easier to use a control port filter.
But PrivCount needs access to the raw event responses, which might or might not work through stem.

For a similar issue in another project, see:
https://github.com/HelloZeroNet/ZeroNet/issues/758

**Comment by teor2345** [comment]
We likely can't port PrivCount to use stem, because we're using Twisted.
We probably have to use txtorcon instead.
So it might be a good idea to just add the control port authentication using custom python code.

**Comment by teor2345** [comment]
(Split off the txtorcon work into #167, I don't think we should do it this close to a release, but it would be nice in a future release.)
