### ISSUE TITLE
should plot and inject scripts be moved to tools

### ISSUE THREAD

**Issue by robgjansen** [privcount/privcount#157]
These scripts have a main function, and are runnable. Isn't the default place for these kinds of scripts in the tools directory? Are there others?

**Comment by teor2345** [comment]
No, because the tool is named "privcount", and it calls plot or inject depending on the command-line arguments passed to privcount.
(We could set up statistics_noise the same way if we wanted to call it on the command-line.)

**Comment by teor2345** [comment]
(Related to #119.)

**Comment by robgjansen** [comment]
Oh yeah, I wrote them that way! Thanks for the reminder :)
