### ISSUE TITLE
Some PrivCount events use strings for flags, others use numbers

### ISSUE THREAD

**Issue by teor2345** [privcount/privcount#189]
The is_dns flag uses 1/0, but the Outbound flag uses "inbound"/"outbound".

This is inconsistent and could cause confusion.
Numbers are probably better: they are shorter and easier to parse and validate.

**Comment by robgjansen** [comment]
So we could use something like `is_outbound` and change it to 1/0.

**Comment by robgjansen** [comment]
Changed to v0.2.0 so we can merge #198.

**Comment by teor2345** [comment]
Looks like neither of us tried to compile this code:
```
  CC       src/or/control.o
src/or/control.c: In function 'control_event_privcount_stream_data_xferred':
src/or/control.c:5838:13: error: format '%s' expects argument of type 'char *', but argument 6 has type 'int' [-Werror=format=]
             "650 PRIVCOUNT_STREAM_BYTES_TRANSFERRED %"PRIu64" %"PRIu32" %"PRIu16" %s %"PRIu64" %ld.%06ld\r\n",
             ^
cc1: all warnings being treated as errors
make: *** [src/or/control.o] Error 1
Exit 2
```
I'll fix it now.

**Comment by teor2345** [comment]
Pushed privcount/tor@d71feb5bfe as trivially correct.
