### ISSUE TITLE
Document each counter and its purpose

### ISSUE THREAD

**Issue by teor2345** [privcount/privcount#209]
We have all these counters, but there is no list of counters and their definition (and why we collect it).

The event definitions help:
https://github.com/privcount/privcount/blob/master/doc/TorEvents.markdown
but they don't cover how PrivCount aggregates events

It would be nice to do this in 0.2.0, but not essential.

**Comment by robgjansen** [comment]
This could be something we do for 0.2.1 along with #179 (it doesn't require share keeper updates), but it's probably not _essential_ there either.

**Comment by robgjansen** [comment]
At one point, each counter was documented in the test files:
https://github.com/privcount/privcount/blob/master/test/counters.noise.yaml
https://github.com/privcount/privcount/blob/master/test/counters.bins.yaml

That listed which position was collecting each counter. That may not be outdated and missing some counter labels.

**Comment by teor2345** [comment]
> That listed which position was collecting each counter. 
We need to provide a *definition* for each counter (that is, what it is meant to be measuring), not just the positions collecting it. Otherwise, we can't tell if it measures what it purports to be measuring.

For an example of the level of detail that is needed, see:
https://github.com/privcount/privcount/blob/master/doc/TorEvents.markdown#privcount-event-field-detail

> That may now be outdated and missing some counter labels.
It is, see #110.

**Comment by teor2345** [comment]
This was done in 1.0.0.
