### ISSUE TITLE
make status messages smarter

### ISSUE THREAD

**Issue by robgjansen** [privcount/privcount#21]
Status messages that are printed look something like this:

```
# tally server
2016-08-05 08:26:00 1470410760.173572 [privcount-ts] [INFO] collection phase is in 'started' state, running for 28648.0008589 minutes (since 1468691880.12)
2016-08-05 08:27:00 1470410820.172474 [privcount-ts] [INFO] --server status: PrivCount is active for 28649 minutes (since 1468691880.12)
# share keeper
2016-08-05 08:18:38 1470410318.544678 [privcount-sk] [INFO] --server status: PrivCount is active for 28640 minutes (since 1468691880.12)
# data collector
2016-08-05 08:18:14 1470410294.422524 [privcount-dc] [INFO] --server status: PrivCount is active for 28640 minutes (since 1468691880.12)
```

There are some usability issues here.
  + The run time (28649 minutes) could be more smartly updated to display weeks, days and hours when the number of minutes is large enough
  + Messages showing when the phase started could include a datetime like `2016-08-05 08:27:00` in addition to the unix timestamp
  + It would be nice to also log the expected end time of the current collection phase (both absolute time like `2016-08-05 08:27:00`, and relative time like `2 hours, 34 minutes`)

I also wonder if there is any other information that would be useful to include in the status messages. In particular, we know that the nodes keep checking in, but it may also be nice to get some indication that the DCs are in fact counting things. I think the DCs store the last time they received an event, maybe they could send this info to the tally server?

**Comment by teor2345** [comment]
I also noticed that the "collection phase will start" message is in fractional minutes, like 0.163490583045 minutes. This would be better as NN.N seconds.

I wonder if there's a built-in python library that does smart time formatting like this.

**Comment by teor2345** [comment]
The DC aggregator stores last_event_time, which can easily be sent to the TS and logged, using the same code as issue https://github.com/privcount/privcount/issues/6 : add contextual info.

It's then easy to log it in the TS status message, and it gets included in the outcome context for free.

**Comment by teor2345** [comment]
https://github.com/privcount/privcount/pull/26 implements the last_event_time feature.
The remaining work in this task is to review all the places we log times, and make them more readable, as described in the task summary.

**Comment by teor2345** [comment]
My branch status-message-times has the time formatting changes, but not added expected end time logging:
https://github.com/teor2345/privcount/commits/status-message-times

I've truncated all times to integer seconds, but I can easily display fractional seconds if you want to. I also made a few minor changes to phrasing of the log messages, to make them more consistent.

I'm not sure exactly what you wanted here:
> It would be nice to also log the expected end time of the current collection phase (both absolute time like 2016-08-05 08:27:00, and relative time like 2 hours, 34 minutes)

Where did you want this logged? TS? DC? SK? All of them?
And how often? Just at the start of the round? Or every status message?

**Comment by robgjansen** [comment]
> I've truncated all times to integer seconds, but I can easily display fractional seconds if you want to.

Integer seconds are great!

> I also made a few minor changes to phrasing of the log messages, to make them more consistent.

Thank you.

> I'm not sure exactly what you wanted here:
...
> Where did you want this logged? TS? DC? SK? All of them?
> And how often? Just at the start of the round? Or every status message?

I was thinking this could be logged in the `--server status` messages, i.e., [on this line](https://github.com/privcount/privcount/blob/master/privcount/tally_server.py#L28). That may require the end time to be sent by the tally server to the other nodes... (I don't recall if that happens currently).

**Comment by teor2345** [comment]
A process note: there are three separate requests in this ticket:
* add the DC last event time to the TS status
* reformat status times
* add the collection end time to the server status

I almost missed the last one. In future, I'll try to split up large tickets into multiple sub-tickets, so I don't miss any of the changes.
