### ISSUE TITLE
Load test privcount using chutney

### ISSUE THREAD

**Issue by teor2345** [privcount/privcount#23]
I'm using the latest version of chutney with the following command, to launch the network and leave it running:
chutney/tools/test-network.sh --flavour basic-min --bootstrap-time -1

And then once the collection run starts, I push data through the network using:
CHUTNEY_CONNECTIONS=1 chutney/chutney verify chutney/networks/basic-min

The Exit has a Control Port 8004, so config.yaml also needs to be updated.

I can't seem to get non-zero results using this setup - I'm not sure whether the Exit is never asked for events, or the collection period is so short that the events never get sent.

**Comment by teor2345** [comment]
The Exit never produces events: it needs the EnablePrivCount option to be set.
Discovered as part of #100.

We want to do this in 0.2.0 so we can test PrivCount locally before deployment.

**Comment by teor2345** [comment]
Now that #100 is implemented, PrivCount sets EnablePrivCount over the control port.
So we can run PrivCount against an unmodified chutney instance, as long as chutney uses a tor that has the PrivCount patch.

**Comment by teor2345** [comment]
We want to do this in 0.2.0 so we can load-test PrivCount with the bandwidth event turned on.

**Comment by teor2345** [comment]
When I load test using chutney, I will need to load test with both a TCP ControlPort and an unix socket ControlPort. Unix sockets typically perform much better than TCP.

**Comment by teor2345** [comment]
We might want to wait to do this until after #19 is completed.

**Comment by teor2345** [comment]
I want to write a script to automate load-testing (or modify run_test.sh), so that it can be run on multiple machines, and we can run it before a release to catch performance regressions.

The script should:
* start a chutney network (time, data volume)
And optionally, one or more of:
  * turn on EnablePrivCount
  * start a privcount data collector for every relay on that network
  * start a sharekeeper and tally server
Then:
* wait until chutney finishes (time)
* display any warning messages from PrivCount (like run_test.sh), and display any warning messages from tor (see chutney trac issue https://trac.torproject.org/projects/tor/ticket/21371 )

Then the operator can monitor performance with and without privcount, and do further diagnostics if needed.

It might not be possible to do this analysis on my macOS laptop, because tor is incredibly slow on it for some reason. I may need to use the spare cores on our canadian server (this is ideal because it's most like the servers we'll be running on), or use a VM somewhere.

**Comment by teor2345** [comment]
This should take 2-4 days of work (a week elapsed time)

**Comment by teor2345** [comment]
(Split this task into 1-day chunks.)

**Comment by teor2345** [comment]
Relay DirPort self-checks via Exits may make getting exact counts difficult (#188). So we should collect baseline zero-traffic figures, determine whether they are reasonable, and use them to adjust load-testing traffic figures.

**Comment by robgjansen** [comment]
We will revisit this only if it turns out to be a problem when running on our relays.

**Comment by teor2345** [comment]
We did this as part of #270.
