### ISSUE TITLE
Don't log the number of events received

### ISSUE THREAD

**Issue by teor2345** [privcount/privcount#245]
This helps with debugging.
It seems safe to provide a count of events to the tally server every checkin period, although, just like the last event time, this does leak some information.

**Comment by robgjansen** [comment]
I'm tempted to allow the tally server some additional information that helps us understand if the data collector is working correctly. But, I don't think the total event count would be strictly safe to collect in all cases. Consider if we only have a single counter enabled, such as the number of circuits. The tally server could keep track of the event counter reported by every data collector over time to work out the actual total count (the number of circuits without the noise added), and also the count that was contributed by *each* individual data collector.

A compromise here would be to just report the last time that any event was received. That way we can tell if a data collector died a long time ago and is no longer receiving events. (But I think PrivCount already works that way.) Implied from the last event time would be whether or not at least one event has occurred during the last checkin period.

**Comment by teor2345** [comment]
I'm turning this into a bugfix: I will remove the privcount code that counts events and replace it with a boolean flag.

**Comment by teor2345** [comment]
This was fixed in e8d922e377e8a86b9c6f05de91aceeec8d42c346 in pull #254, the commit message does not describe all the changes. Oops!
