### ISSUE TITLE
add license

### ISSUE THREAD

**Issue by robgjansen** [privcount/privcount#247]
Add license file.

**Comment by robgjansen** [comment]
Any objections to the following license? It's a BSD-style license with an extra clause clarifying that the US Government claims no copyright.

```
To the extent that a federal employee is an author of a portion of
this software or a derivative work thereof, no copyright is claimed by
the United States Government, as represented by the Secretary of the
Navy ("GOVERNMENT") under Title 17, U.S. Code. All Other Rights 
Reserved.

Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions are
met:
    * Redistributions of source code must retain the above copyright
notice, this list of conditions and the following disclaimer.
    * Redistributions in binary form must reproduce the above
copyright notice, this list of conditions and the following disclaimer
in the documentation and/or other materials provided with the
distribution.
    * Neither the names of the copyright owners nor the names of its
contributors may be used to endorse or promote products derived from
this software without specific prior written permission.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
"AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
(INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
GOVERNMENT ALLOWS FREE USE OF THIS SOFTWARE IN ITS "AS IS" CONDITION
AND DISCLAIMS ANY LIABILITY OF ANY KIND FOR ANY DAMAGES WHATSOEVER
RESULTING FROM THE USE OF THIS SOFTWARE.
```

**Comment by robgjansen** [comment]
@TariqEE , and @teor2345 - as authors, do you agree to the use of the above license?

**Comment by teor2345** [comment]
I agree to the use of the above licence for my contributions to the PrivCount python code.

> It's a BSD-style license with an extra clause clarifying that the US Government claims no copyright.
And an extra clause disclaiming government liability:
> GOVERNMENT ALLOWS FREE USE OF THIS SOFTWARE IN ITS "AS IS" CONDITION
AND DISCLAIMS ANY LIABILITY OF ANY KIND FOR ANY DAMAGES WHATSOEVER
RESULTING FROM THE USE OF THIS SOFTWARE.

I am not a lawyer, but I think these changes to the standard 3-clause BSD licence are minor. Otherwise I would consult a lawyer. I assume your employers have done so. I will ask mine if they wish to do the same.

Also, @robgjansen, can you confirm that the tor patch is covered by the existing tor licence?
(Without disclaimers?)

**Comment by teor2345** [comment]
@robgjansen, GitHub only shows people with accounts (I think).
The command you want is:
```
privcount$ git shortlog -sn
   205  teor
    94  Rob Jansen
    21  Tariq
     3  Ian Goldberg
     3  teor (Tim Wilson-Brown)
     1  Tariq Elahi
```
It might be worth emailing Ian and Tariq.

**Comment by robgjansen** [comment]
I contacted Tariq E., Ian G., and George D. and they are all OK with this license.

**Comment by teor2345** [comment]
Ok, I will add a header to each file when I do the mass changes.

**Comment by robgjansen** [comment]
I think we are going to add the license to a LICENSE file in the top level directory, and then the header of each file can just contain a short blurb that points to the LICENSE file. Is that consistent with your plan?

**Comment by teor2345** [comment]
> I think we are going to add the license to a LICENSE file in the top level directory, and then the header of each file can just contain a short blurb that points to the LICENSE file. Is that consistent with your plan?

Yes, I will follow the recommended best practice, or what Tor does.

**Comment by teor2345** [comment]
I added a short header to the LICENSE file and to each code file, and the README.
I didn't add anything to documentation or (test) data files.
