### ISSUE TITLE
Switch to using semantic versioning

### ISSUE THREAD

**Issue by teor2345** [privcount/privcount#259]
Hi @robgjansen, can we switch to using semantic versioning?

    Given a version number MAJOR.MINOR.PATCH, increment the:
    1. MAJOR version when you make incompatible API changes,
    2. MINOR version when you add functionality in a backwards-compatible manner, and
    3. PATCH version when you make backwards-compatible bug fixes.

http://semver.org/

For example, when we:
* change counter names, we go from 0.2.0 to 1.0.0
* add new events or new counters, we go from 0.2.0 to 0.3.0
* fix bugs, we go from 0.2.0 to 0.2.1

This would mean that our current milestones become:
* 0.2.0 -> 1.0.0 (rename counters, protocol encryption changes, event changes, others)
* 0.2.1 -> 1.1.0 (add alexa counter)
* 0.2.2 -> 1.2.0 (add hidden service events and counters) or 2.0.0 (modify existing events)
* 0.3.0 -> Security (a meaningful name)
* 0.4.0 -> Robustness

**Comment by robgjansen** [comment]
Yes, please go ahead.

**Comment by teor2345** [comment]
I have modified the versions in the bug tracker, and documented how we do versioning in a branch.
