### ISSUE TITLE
Protocol maximum line length is too short for 8 data collectors

### ISSUE THREAD

**Issue by teor2345** [privcount/privcount#270]
This is probably what we'll have in the experimental network, so I'll fix it.

**Comment by teor2345** [comment]
So apparently when I made the counter names longer (on average), added another counter, changed the encryption and all those things, I made the ShareKeeper initial line really, really long.

Since we will have 12+ relays in the experimental network, I think this means we need to make the line at least 1MB. So let's make it 10MB to be safe. (The limit for unauthenticated clients is still 255 bytes.)

I bet the traffic model made this bigger, too. @robgjansen, how many more states will you have in the traffic model(s) you want to collect?

**Comment by robgjansen** [comment]
@teor2345 I'll send you the actual model I plan to start with in an email.

**Comment by teor2345** [comment]
@robgjansen, my initial tests show that the production traffic model adds about 720 counters. (The test traffic model adds about 20 counters.)

I think this means that we will be sending around 5MB of data per ShareKeeper each time we start or stop. And if we have 6 ShareKeepers, that means around 30MB of data will be sent.

That's not a huge concern, but we probably can't afford to scale up by another 10x or 100x.

**Comment by teor2345** [comment]
As discussed, I will run a network with 20 data collectors and 10 share keepers.

**Comment by teor2345** [comment]
When I run a network with 25 data collectors, PrivCount generates 8MB TS to SK start lines:
`
2017-05-18 16:51:16 1495090276.289419 [privcount-ts] [WARNING] Generated line of length 8327859 exceeded safe length of 5242880, keeping validated connection to remote: 127.0.0.1:53954 local: 127.0.0.1:20001
2017-05-18 16:51:21 1495090281.157053 [privcount-sk] [WARNING] Received line of length 8327859 exceeded safe length of 5242880, keeping validated connection to remote: 127.0.0.1:20001 local: 127.0.0.1:53954
`

**Comment by teor2345** [comment]
With 20 data collectors and 10 share keepers:
```
test/run_test.sh -I . -x -z -s chutney -n basic-025 -p `seq 8000 8019` -k 10
```

And config.chutney.yaml with:
```
    collect_period: 180
    event_period: 20
    checkin_period: 20
```

I get:

2017-05-18 17:14:13 1495091653.190867 [privcount-ts] [WARNING] Generated line of length 6704744 exceeded safe length of 5242880, keeping validated connection to remote: 127.0.0.1:59357 local: 127.0.0.1:20001

So we should probably increase the limit to 20MB (warnings will start at 10MB).

**Comment by teor2345** [comment]
I added logging for the number of bins, which will give us a better idea of how the line length scales.
With the new traffic model, this is:
    795 counters (1330 bins)
With the old traffic model, this is:
    90 counters (625 bins)
With no traffic model, this is:
    64 counters (599 bins)

**Comment by robgjansen** [comment]
I believe the revisions on the traffic model, which happen at the end of a counting phase, will only adjust the transition and emission probabilities, but it does not adjust the number of states. So, I don't _think_ the revisions will increase the model size. There is a chance that zero probabilities become non-zero after an iteration (or vice versa), but I don't know how that affects the model size.

The revisions to the model happen here, in case you want to double check (Nick H. wrote this code):
https://github.com/privcount/privcount/blob/master/privcount/traffic_model.py#L359

**Comment by teor2345** [comment]
> There is a chance that zero probabilities become non-zero after an iteration (or vice versa), but I don't know how that affects the model size.

Transitions with zero probabilities have no counter.

Transitions with zero counts have their probabilities multiplied by 0.1 every revision. It would take about 15 revisions for a counter with probability 0.1 to become zero.

So the number of counters is effectively constant.
We currently have 730 counters in the traffic model, we could afford to have about 2000 before we reach the warning limit in the code (and 5000 before protocol failure). I think this is an acceptable limit: I'll merge the code.
