### ISSUE TITLE
Why are the Ratio bins asymmetric around 0?

### ISSUE THREAD

**Issue by teor2345** [privcount/privcount#279]
Hi @robgjansen, is there any reason why the PrivCount ratio bins don't have a [-0.00000000000001, 0.0] bin?
```
        - [-1.0, 0.0]
        - [0.0, 0.00000000000001]
        - [0.00000000000001, 1.0]
        - [1.0, 2.0]
```

**Comment by robgjansen** [comment]
I *think* those were just to see if we actually get non-zero ratios as opposed to small ratios in small tests with no noise added; basically, to verify that counts were actually occurring. In all of the "real" measurements that we carried out on Tor that involve ratios, I used:

```
    bins:
    - - -.inf
      - -1.0
    - - -1.0
      - 1.0
    - - 1.0
      - .inf
```

**Comment by teor2345** [comment]
> I think those were just to see if we actually get non-zero ratios as opposed to small ratios in small tests with no noise added

We did in my recent tests. Not sure if this is important.
