### ISSUE TITLE
Do you want to revise the traffic model MTU for overheads?

### ISSUE THREAD

**Issue by teor2345** [privcount/privcount#281]
Hi @robgjansen, Exits measure the exact number of application bytes sent, minus any Tor or network overheads. This means that the MTU of 1500 bytes might not be accurate.

For example:
* Tor imposes a 14-byte overhead for every 498 bytes of cell data
* Tor imposes a ~2% cell overhead for acknowledgement cells (in the opposite direction)
* TCP imposes a 20 byte overhead per 1500 byte Ethernet packet
* there may be other smaller overheads on both the network and in Tor.

Or is this level of precision not needed?

**Comment by robgjansen** [comment]
The important thing is that we are consistent in what we call a "packet"; I think 1500 bytes gets us close enough, and I don't think the extra precision would be worth the effort.
