### ISSUE TITLE
Count zero EntryClientIPActiveCircuitCounts in a separate bin

### ISSUE THREAD

**Issue by teor2345** [privcount/privcount#306]
We are ignoring zeroes in EntryClientIPActiveCircuitCount and EntryClientIPInactiveCircuitCount, but this doesn't make much sense in a histogram.

**Comment by teor2345** [comment]
I will document this behaviour for now. If we want to change it, we can delay this release, or fix it in a future release.

**Comment by teor2345** [comment]
Deferring: I don't think this matters (and it can be deduced by calculating the number of 10 minute intervals in the collection period * the number of relays - sum(bins)).

**Comment by robgjansen** [comment]
> (and it can be deduced by calculating the number of 10 minute intervals in the collection period * the number of relays - sum(bins))

If we sum(bins), then we are summing noise, which is different than having a zero bin that only has one instance of noise added.

**Comment by teor2345** [comment]
> (and it can be deduced by calculating the number of 10 minute intervals in the collection period * the number of relays - sum(bins))
> If we sum(bins), then we are summing noise, which is different than having a zero bin that only has one instance of noise added.

Ok, I will make sure we fix this in 1.0.1 or later.
