### ISSUE TITLE
_get_inter_packet_delays does not track inter-packet delays

### ISSUE THREAD

**Issue by robgjansen** [privcount/privcount#312]
I think I found a bug in `_get_inter_packet_delays `. It looks like we are tracking packet delay as the time since the start of the stream, rather than inter-packet delay as the time since the most recently received packet. https://github.com/privcount/privcount/blob/master/privcount/traffic_model.py#L274

This may not need to be fixed if it is removed as part of #292.

**Comment by teor2345** [comment]
Deferring to 1.1.0 as discussed by email.

**Comment by teor2345** [comment]
If we find out that the traffic model does run at acceptable speeds on our relays, we'll regret not fixing this in 1.0.0.
