### ISSUE TITLE
Is running from the repo necessary? Is privcount just trying to get its version?

### ISSUE THREAD

**Issue by pastly** [privcount/privcount#353]
It looks like privcount just tries to determine its own git revision version. If its just for logging purposes, it should probably fail quietly in the background and not worry about it. Or perhaps "compile in" the version such that no check is necessary. It's possible for me to do a `git pull` without a follow up `pip install -I .`, and if I understand pip correctly, I have to do the latter to update privcount.

```
(venv) [mtraudt@temp2 StanMarsh]$ privcount dc privcount.config.yaml
2017-06-14 22:25:19 1497493519.835744 [privcount-dc] [INFO] using config file at '/home/mtraudt/run/StanMarsh/privcount.config.yaml'
fatal: Not a git repository (or any parent up to mount point /home)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
2017-06-14 22:25:19 1497493519.840010 [privcount-dc] [WARNING] Git revision check ['git', 'rev-parse', '--short=16', 'HEAD'] returned 128 cmd "['git', 'rev-parse', '--short=16', 'HEAD']" output ""
2017-06-14 22:25:19 1497493519.840202 [privcount-dc] [INFO] running dc privcount version 1.0.1 (protocol PRIVCOUNT-100, git-(no revision))

```

**Comment by teor2345** [comment]
> It looks like privcount just tries to determine its own git revision version. If its just for logging purposes, it should probably fail quietly in the background and not worry about it.

Yes, I agree, this should be downgraded to INFO.

> Or perhaps "compile in" the version such that no check is necessary.

This is possible. But I'm not sure it's worth the extra effort: the PrivCount version number has a matching git tag with the release git revision.

This code exists so I have some way of knowing which revision I was running during development. And it helps if there are problems during a deployment containing different revisions: the client revisions are reported to the tally server, and the tally server reports its revision to clients.

> It's possible for me to do a git pull without a follow up pip install -I ., and if I understand pip correctly, I have to do the latter to update privcount.

It's also possible to modify the source and install it without committing it.

Regardless of how we determine the git revision, it's only ever going to be a best guess.
