### ISSUE TITLE
The key expansion & sampling functions used to produce blinding factors are unproven

### ISSUE THREAD

**Issue by teor2345** [privcount/privcount#37]
We should replace them with standard crypto library implementations, or redesign blinding so that the construction is obviously correct.

We've already seen bugs #34, #35, #38 arise from the current construction.

**Comment by teor2345** [comment]
Ideally, we could use python's random.randrange(), but it's documented to produce unevenly distributed values in versions < 3.2.

**Comment by teor2345** [comment]
One option is to use a separate 8-byte random number for each counter. This can be produced directly from os.urandom() as long as q is 2**64 (see #39).

Another option is to use a KDF from the python cryptography library:
https://cryptography.io/en/latest/hazmat/primitives/key-derivation-functions/

**Comment by teor2345** [comment]
@robgjansen: what would you prefer:
* using a per-bin random number for blinding?
* modifying the privcount code to use a KDF from the python cryptography library?
* leaving the custom KDF as-is?
  * (after https://github.com/privcount/privcount/pull/42 is merged, of course)

I am concerned about @ajohnson-nrl's comments about using a SHA256 keyed hash construction to produce the blinding values, particularly given how many bugs I've found in that area of the code.

**Comment by robgjansen** [comment]
The existing custom KDF is leftover from PrivEx, and if we don't think it is correct, then we should change to something that we know is correct. I think the 8 byte approach could work, but if there is a better standard way of generating arbitrary length random numbers, that would be ideal. I'd like us to consult with someone more familiar with this than I.

**Comment by ajohnson-nrl** [comment]
After a bit a googling, it looks like an ideal solution here is to use random.SystemRandom().randrange(q). The random.SystemRandom class implements most functions in random() but with os.urandom() as the source. We do not want a Key Derivation Function (KDF) here, as the properties that define a KDF are not what we need. A good KDF should (i) make it hard to derive the input from the output and (ii) perform any needed format transformation to turn its input into something in the keyspace of the desired cryptographic function. Neither of these properties implies a uniformly random distribution over the output space, and in fact I would be surprised if any common KDF produced a uniform distribution.

**Comment by teor2345** [comment]
We can't use `randrange()`, because it produces slightly uneven distributions in python versions < 3.2 (and even then, I'd want to check the algorithm they're using).

https://docs.python.org/3.5/library/random.html#random.randrange

I think that out best option is to use `random.SystemRandom.getrandbits((q-1).bit_length())`, and then discard any values `> (q-1)`. This makes sure we don't re-introduce #34. And it avoids the complexities of the 8-byte approach, which is actually quite hard to implement in a performant manner. (See commit 859d9c5, where I calculate a byte length from a bit length, then pad the extracted bytes in the correct endianness, to yield an integer that's slightly larger than q, then discard any values `>= q`.)

And if q is `2**64` (or any power of 2), we won't end up discarding any values at all, because getrandbits produces longs in `{0, ... , 2**k - 1}`. And in the worst-case scenario where q is `2**k + 1`, we will discard just under half the values, which avoids re-introducing #41.

We can also ditch hash_id when this is implemented, which deals with #36.

https://docs.python.org/2.7/library/random.html#random.getrandbits
https://docs.python.org/2.7/library/stdtypes.html#long.bit_length

**Comment by ajohnson-nrl** [comment]
Ah, yes, you had mentioned the issue with randrange() before, sorry. If getrandbits() doesn't suffer the same issue, then this should work. I assume that you retry upon failure (i.e. when then random number is >= q).

**Comment by teor2345** [comment]
When I fix this, I also want to increase the maximum tested modulus in test_counters.py. This will ensure we don't have any subtle implementation bugs that happen when the modulus exceeds a C long.

**Comment by teor2345** [comment]
I almost have this code written, but encrypting a large message (like a list of blinding factors) using RSA public keys is insecure. The recommended solution is to encrypt a one-time symmetric key using RSA, and the rest of the data using that symmetric key:

https://www.sitepoint.com/encrypt-large-messages-asymmetric-keys-phpseclib/

I'll use fernet, a high-level symmetric encryption algorithm built-in to the python cryptography library:

https://cryptography.io/en/latest/fernet/

I also need to serialise the blinding factors themselves. I want to do this with yaml.safe_load, because we're taking input from the network. But it doesn't support longs. The easiest solution to this may be to convert the longs to strings before dumping the yaml, and convert them back after using safe_load.

**Comment by teor2345** [comment]
yaml.dump() will dump most longs as strings, and every so often, it will dump a long as a tagged python object. I think it's trying to preserve the type of the smaller integers, which would otherwise be encoded as int().

(As an aside, I uncovered this issue because I was testing with q / modulus at 2**70 - I think we should keep it that size to uncover subtle bugs like this.)

I could tell yaml.safe_load() that longs are safe, but they might not be. I think we should just use strings, which are definitely safe. Of course, we'll need to cast them to long on the way out.

**Comment by robgjansen** [comment]
Using strings seem fine to me.
