### ISSUE TITLE
Allow PrivCount to limit cell events from Tor

### ISSUE THREAD

**Issue by robgjansen** [privcount/privcount#418]
There are use-cases where PrivCount may only want to process the first N cells on a Tor circuit, and ignore the rest. Currently, this needs to be done from the PrivCount side, meaning that PrivCount will still be receiving and parsing all of the cell events that it doesn't care about. Let's add a feature to allow PrivCount to tell Tor not to even emit the events in the first place, which should save a considerable amount of processing overhead during a measurement.

- [x] Add Tor feature to allow configurable per-circuit cell limit
- [x] Add config option in PrivCount to enable a maximum per-circuit cell limit and set the limit in Tor via the Tor control protocol

**Comment by robgjansen** [comment]
Initial implementation is done in the issues referenced above. Waiting for code reviews and testing.

**Comment by teor2345** [comment]
Merged to tor privcount-master as 948ffe826d with compilation and whitespace fixes.
Merged to privcount master as d457e3c with test improvements.
