### ISSUE TITLE
privcount/tor should be linked to torproject/tor

### ISSUE THREAD

**Issue by robgjansen** [privcount/privcount#419]
If you push the fork button on https://github.com/torproject/tor, then the new repository gets linked to the torproject main repository. This makes it easier to submit pull requests across accounts.

If we want to do this, I think we would want to rename privcount/tor, then create a new linked repository using the fork button, and then push the branches and delete the old repository. I think we would lose some history, collaborators, and other settings, so I'm not sure that it's worth it.

See https://github.com/robgjansen/tor for an example.

**Comment by teor2345** [comment]
We would also need to re-create any forks of privcount/tor, which would be a pain.

But you could ask Github support to fix this for you - I'm sure it's happened before, hopefully they have a way of fixing it.

**Comment by robgjansen** [comment]
Thanks for the suggestion. I sent a request to Github support.

**Comment by robgjansen** [comment]
Here was the response:

> Thanks for reaching out! I'm afraid we can't retroactively make a repository a fork if it wasn't originally created as one, due to how fork networks currently work. You would have to create a new repo using the "Fork" button and recommit any changes. Sorry we couldn't be of more help, but let us know if you have any other questions!

**Comment by teor2345** [comment]
Then it doesn't seem worth it to me: the workaround is to fork the project you want to make a pull request to, and then push a branch to that fork, which works well for me.

(I use the same local repository for tor master and tor privcount, and it works fine.)
