### ISSUE TITLE
Tests don't run on CentOS 7

### ISSUE THREAD

**Issue by robgjansen** [privcount/privcount#448]
Currently, after a fresh clone of `git@github.com:privcount/privcount.git` and installing all of the requirements into a fresh virtualenv, the `run_test.sh` script prints the following and exits:

```
(privcountenv)[rjansen@sol privcount]$ ./test/run_test.sh -I .
Selecting data source inject...
Installing latest version of privcount from '.' ...
Processing /scratch/privcount_test/privcount
Installing collected packages: PrivCount
  Running setup.py install for PrivCount ... done
Successfully installed PrivCount-1.1.0
Checking that all events have counters, increments, tests, and docs:
Checking event consistency:
rm: cannot remove ‘./test/*.event_names’: No such file or directory
Number of events:
wc: ./test/*.c.event_names: No such file or directory
wc: ./test/*.h.event_names: No such file or directory
   9 ./test/counter.py.event_names
   8 ./test/data_collector.py.event_names
   8 ./test/inject.py.event_names
   8 ./test/events.txt.event_names
   9 ./test/TorEvents.markdown.event_names
```

Presumably it is not running any of the test cases.

I don't think that `rm` or `wc` should cause the script to fail, so I'm not sure what is going on. What else can I provide to help debug this problem?

**Comment by teor2345** [comment]
> I don't think that rm or wc should cause the script to fail, so I'm not sure what is going on

The script uses `set -e`, so any command failure causes the script to exit.

I had assumed that there would always be a tor in `privcount/../tor-privcount`.
To fix the issue, I stoped making that assumption, and added an informative message instead.

(You can run the default inject target without tor, but running `./run_test.sh -s tor` needs tor, and `./run_test.sh -s chutney` needs tor and chutney.)
