### ISSUE TITLE
Make requirements.txt use the latest versions

### ISSUE THREAD

**Issue by teor2345** [privcount/privcount#48]
Are we concerned about updates to our dependencies breaking PrivCount code?

**Comment by robgjansen** [comment]
We shouldn't be worried about dependencies in my opinion, since they are pretty easy to set up. The reason requirements.txt has versions is probably because I didn't think too much about it and ran the default command that produces that file (`pip freeze` I think).

**Comment by teor2345** [comment]
Ok, I think we should use the latest available versions of each dependency, so that we get security updates.

Since this is a security issue, putting it in 0.2.0.

**Comment by teor2345** [comment]
I turned all the package requirements into >= rather than ==.
I also added requirements-plot.txt for the privcount plot requirements.

Testing using #72 shows that the event numbers changed slightly due to event timings. But nothing of significance was different with the newer library versions.

**Comment by teor2345** [comment]
In fact, upgrading library versions makes the event jitter disappear. Only the times differ, rather than the counts. This makes the diff from #72 work much better -  the diff between rounds is empty (it automatically ignores times).
