### ISSUE TITLE
The PrivCount handshake relies on floating-point arithmetic

### ISSUE THREAD

**Issue by teor2345** [privcount/privcount#53]
The PrivCount handshake relies on a floating-point magic number that is multiplied by a random client and server cookie, then rounded to an integer.

Floating-point arithmetic can be inaccurate, across processor flags or processor versions or architectures or compiler options or OSes. This could cause intermittent or permanent handshake failures.

I think we need to fix this in 0.3.0, because it is a reliability issue. But I'd be happy to fix it in 0.2.0 if @robgjansen would like to push out the deadline.

**Comment by robgjansen** [comment]
v0.3.0 seems fine to me.

**Comment by teor2345** [comment]
#78 fixes this issue by replacing floating-point arithmetic with a HMAC.
