### ISSUE TITLE
The PrivCount run_tests.sh can run forever

### ISSUE THREAD

**Issue by teor2345** [privcount/privcount#54]
If one of the privcount processes fails, but the others keep on going, run_tests.sh can run forever.
This is required for #46 to fail the unit tests correctly when SHA256 is not supported (versions of cryptography < 1.4).

**Comment by robgjansen** [comment]
Ahh, I think I *just* ran into that on my traffic classification branch. run_test.sh was running forever and I was wondering why; something must have failed.
