### ISSUE TITLE
add contextual info to tally server results file

### ISSUE THREAD

**Issue by robgjansen** [privcount/privcount#6]
We should add the sigma values that were used for each counter to the results file that the tally server writes. We should also add the fingerprints of the relays that were used by the data collectors. This will make it easier to interpret and process the results later.

**Comment by teor2345** [comment]
I have submitted a pull request for this branch: https://github.com/privcount/privcount/pull/24

The contextual information now consists of:
* Count: Q, Sigmas
* DataCollector:
  * all items in status
    * these use the latest value reported
  * fingerprint, nickname, address, orport, dirport, tor version
    * these are queried from the control port and sent in the status message
    * I chose these values so we could easily debug deployments
* ShareKeeper:
  * all items in status, except the public key blob
    * these use the latest value reported
* TallyServer:
  * IP & Port
* Time:
  * Padding, Period, Start, Stop

I've tested it against the injector and a non-privcount tor, but I can't seem to get it to return non-zero results with chutney and a privcount-patched tor. But this doesn't work on privcount master either, so it's probably my setup.

I've opened a separate issue for that: https://github.com/privcount/privcount/issues/23
