### ISSUE TITLE
PrivCount self-test with 30 second collect_period lasts for 60 seconds 

### ISSUE THREAD

**Issue by teor2345** [privcount/privcount#7]
The PrivCount self-test config.yaml has a 30 second collect_period.
But the privcount.tallies JSON files it produces have a 60 second time range, as do the start/stop events logged by the data collector.

**Comment by teor2345** [comment]
Rob says that the tally server runs its main loop every minute, this means that every phase of the protocol takes at least a minute. We could configure  a much shorter period here, perhaps a second.
We could also make the clients check in every second.
This could speed things up significantly.

**Comment by teor2345** [comment]
I've written a script that runs a privcount collection round, based on the instructions in test/README.markdown. It also measures the elapsed time. These changes are in https://github.com/teor2345/privcount/tree/better-self-test

The script reports each privcount round takes 199 seconds to install, run, produce results, and plot them. 

I tried reducing the client check-in period to 1 second, and the collection time to 10 seconds. But that didn't make any difference to the time it takes to produce results.

I think the tally server event loop timing swamps all the other times involved. It seems that each state: prepare, collect, tally takes 60 seconds, for a total of ~180 seconds. My next step is to make the loop time configurable.

**Comment by robgjansen** [comment]
This makes sense, and a configurable event loop time seems very handy for testing.

**Comment by teor2345** [comment]
I think we need to satisfy the following constraints:
* The round time should be an integer multiple of the client check-in time.
* The client check-in time should be an integer multiple of the event loop time.

This makes sure that things complete on time.

We should prioritise the round time, and never change it, because it's the most important setting. The others can adapt as needed. Here's an adaptive algorithm:
* allow the event loop time to be configurable
* if the client check-in time time is greater than the round time, reduce the client check-in time to the round time (and log a message to that effect)
* otherwise, if the client check-in time time is less than the round time, and does not divide evenly into the round time, warn the user that the round finish may be delayed
* if the event loop time is greater than the client check-in time, reduce the event loop time to the client check-in time (and log a message to that effect)
* otherwise, if the event loop time time is less than the client check-in time, and does not divide evenly into the client check-in time, warn the user that the round finish may be delayed

**Comment by teor2345** [comment]
Actually, that scheme was way too complicated, and doesn't match the actual timing constraints:
* Added event_period as a configurable time for the TS refresh_loop
* Made the default event_period and checkin_period 60 seconds
* Make sure there are at least two event_periods and checkin_periods in each collect_period (otherwise the TS can hang indefinitely)
* Log an info-level message when the checkin_period is greater than the event_period, because client status changes can take a while to propagate (this only really matters when the collect_period is small)
* Updated the test config.yaml to implement these rules

It's possible to get test times down to 9 seconds with this change, using a collection period of 2 seconds, and event and checkin periods of 1 second. This is much better than 3 minutes. But some events are cut off, which is ok.

This patch doesn't remove the need for the injector --simulate flag. I don't think it's that important either way.

This patch almost fixes the original file name bug where the times are out. Sometimes, there is an extra second in the file time - again, much better than 30 seconds. This is likely due to clock skew and integer rounding. I think it's better to be accurate, and use the actual time, even if that doesn't quite match the expected time for the round (for example, if the round finishes early).

But I'm happy to make that time consistent by using something like:
`
stop_time = min(actual_stop_time, start_time + collect_time)
`

What do you think, @robgjansen?

**Comment by robgjansen** [comment]
I would prefer that we be accurate and use the actual time rather than rounding. In any case, the difference in stop time is likely to be insignificant for normal (longer) rounds.

**Comment by teor2345** [comment]
After thinking about it, I suspect that the difference in stop time is a TS artifact due to the clock_skew - the actual collection times on the data collectors should be accurate, because they do the timing themselves.

So we might just want to warn users that the final time includes a network rtt - or is that even worth it?

**Comment by robgjansen** [comment]
Given that I expect most collection rounds to last on the order of days under normal operation, I think a few hundred milliseconds to a few seconds for clock skew may not even be worth worrying about.
