### ISSUE TITLE
Any client can connect to the PrivCount Tally Server

### ISSUE THREAD

**Issue by teor2345** [privcount/privcount#78]
In 0.1.0, the PrivCount protocol was protected by a secret floating-point value PRIVCOUNT_HANDSHAKE_MAGIC, embedded in protocol.py.

Now the source code is public, anyone can connect to the PrivCount tally server, and attempt to impersonate any of the tally server's clients.

It's even possible to brute-force the handshake:
- client and server choose random values in [0.0, 1.0) with 6 decimal digits (~19 bits of entropy)
- these values are multiplied together with PRIVCOUNT_HANDSHAKE_MAGIC (759.623), then rounded to the nearest 6 decimal digits, giving at most 9 digits in [0.0, 759.623) (~29 bits)
- multiplying two random numbers [0.0, 1.0) gives a random number in [0.0, 1.0), which is biased towards zero,
- even without the bias, 29 bits are easily brute-forced in a few million operations, which could easily be performed during a week-long collection.

Here's what we could do about that:
1. Try to fix the existing handshake:
    \* make PRIVCOUNT_HANDSHAKE_MAGIC configurable, and require each node to use the same magic value,
    \* impose a minimum on PRIVCOUNT_HANDSHAKE_MAGIC, and increase the length of client_cookie and server_cookie,
    \* round fewer digits, preferably only rounding to sys.float_info.dig,
    \* and even then we'd still have to deal with the bias issue.
2. Remove the existing handshake and just let all clients connect
3. Replace the existing handshake with symmetric encryption using a shared key, using the existing symmetric encryption code.

**Comment by robgjansen** [comment]
My tally server was initially seeing random connections from port scanners and it was causing problems, so I quickly added this handshake mechanism to avoid those. It was never meant to be secure. #2 was meant to add proper client authentication to make this handshake unnecessary.

I would suggest not falling back to letting all clients connect if we don't have a way to quickly ignore port scanners.

I'm not sure this handshake needs to be cryptographically secure, because even if someone brute forces the handshake, they will not posses the client keys and so will not be able to impersonate them. Is that right?

**Comment by teor2345** [comment]
That's right, once #2 is implemented.
But it's scheduled for 0.4.0, did you want to move it to 0.2.0?

**Comment by robgjansen** [comment]
I prefer that we don't add more work to 0.2.0 since it's already overdue. It seems like #88 may obsolete #2, though, IIUC.

**Comment by teor2345** [comment]
We will do a quick implementation of option 1 for 0.2.0.

**Comment by teor2345** [comment]
I think this might take a little more work - we need to not only make the secret configurable, but also replace the multiplication operation with something more robust.

Multiplication suffers from a bias towards zero that comes from multiplying two numbers in [0.0, 1.0]. A simple and secure way to remove this bias is to use a hash as the combination function, rather than multiplication.

(Also, the current handshake can be trivially defeated by using 0.0 as the client cookie, and 0.0 as the password, regardless of the magic value. Using multiplication also means that the order of the magic, server, and client parts is interchangeable - which doesn't lead to any obvious vulnerabilities, but should probably be avoided.)

So `password = handshake_magic * server_cookie * client_cookie` becomes `hash_result = H(privcount_secret_auth_key,  server_cookie | client_cookie)`.

If we use a HMAC, then magic becomes the key, and we do `hmac_result = HMAC(privcount_secret_auth_key, server_cookie | client_cookie)`.
https://tools.ietf.org/html/rfc2104

The cryptogaphy library has a HMAC class with a `verify()` method. It should be very easy to wrap in a utility function, just like we wrap encryption and decryption.
https://cryptography.io/en/latest/hazmat/primitives/mac/hmac/

And if we're using a HMAC, magic needs to be at least L bytes long, where L is the output length of the hash function. And if we're doing that, we might as well make all the parameters L-byte base64-encoded strings.

So each encoded parameter will be ceil(L*8/6) bytes long, or 43 bytes for SHA256.

The handshake proceeds as follows, with the following lengths:
HANDSHAKE1 + ' ' + server_cookie -> 54
HANDSHAKE2 + ' ' + client_cookie + ' ' + hmac_result -> 65
HANDSHAKE3 SUCCESS -> 18
HANDSHAKE3 FAIL -> 15

This handshake authenticates to the server that the client knows the secret, without revealing the secret on the wire. It is susceptible to replay attacks and server impersonation (a malicious server can simply say SUCCESS regardless of the client response). We'll implement bidirectional auth in #78, and replay resistance in #85. (These implementations will use a proven authenticated encryption construct.)
