### ISSUE TITLE
automatic sigma value calculation

### ISSUE THREAD

**Issue by robgjansen** [privcount/privcount#9]
Aaron has a script that he has to run for me every time we do a new collection phase. We can incorporate the calculation that his script performs into PrivCount so that the sigma values that are used to add noise to the counters are calculated automatically. We would probably give as input to PrivCount a file that provides estimates for the number of circuits, streams, clients, etc. and then use Aaron's code to produce the sigmas.

**Comment by ajohnson-nrl** [comment]
I am attaching the Python script that I have been using to perform the automatic sigma calculation (I had to add a .txt extension to get GitHub to accept it). That file contains the privacy sensitivities and the estimates that we used during data collection. The estimates themselves are a bit messy due to repeated partial updating and collection. However, you can run the file and get output, and all of the relevant logic is contained in get_opt_privacy_allocation().

I changed get_opt_privacy_allocation() to avoid the issue that I had mentioned before via email about possibly failing certain checks. The current logic is as described in the final version of the paper and is what I would suggest for automated sigma evaluation in PrivCount.

[statistics_noise.py.txt](https://github.com/privcount/privcount/files/431188/statistics_noise.py.txt)

**Comment by teor2345** [comment]
Inputs (at TS):
* privacy budget: total epsilon & delta
  * each statistic consumes some of the epsilon and delta
* estimates of the values of each counter
  * (it is possible to run a round, then input the counts from the previous round, but we don't plan on making this automated)
* excess noise ratio:  how many data collectors (or some other calculation)
* tolerances should come with defaults, but be configurable if we need to
* all of these inputs should be cast to doubles on the way in (inaccuracy doesn't matter, as the estimates are the only numbers that are likely to be larger than 2**53, and we add more noise than the inaccuracy)

Calculation:
* deterministic, produces exactly the same results with the same inputs
  * (apart from floating-point inaccuracy)

Outputs (at TS):
* a sigma value for each counter
* the expected noise ratio (based on the estimated counter values)

Usage:
* TS sends sigma values to the DCs
  * replacing existing config file
  * TS can take a config file of sigma values or the input parameters for automatic noise
* TS sends sigma values to the SKs
  * this allows us to check if noise has changed so we can implement #22

**Comment by teor2345** [comment]
We need to do #44 before this task, so that the noise weight can be used with the calculated sigma values

**Comment by teor2345** [comment]
The process of automatic noise calculation needs to be documented in a doc/ directory, but not to the point of repeating the PrivCount paper.

**Comment by teor2345** [comment]
I have started working on this in my auto-stats branch
https://github.com/teor2345/privcount/tree/auto-stats

**Comment by teor2345** [comment]
Made some minor fixes here:
https://github.com/teor2345/privcount/tree/auto-stats-v2

Now we are configuring the noise weights at the TS in pull request #76, I can start on this task.

**Comment by teor2345** [comment]
I need to add the existing sigma calculation at the end of the file to the unit tests. I think this is more efficient than writing my own unit tests.

**Comment by teor2345** [comment]
I have moved the sigma config from the DCs to the TS, and added some basic validity checks:
https://github.com/teor2345/privcount/tree/auto-stats-v3

I still need to:
* allow the TS to calculate the sigmas from the total epsilon, total delta, and estimated values
  * these should all be cast to double by the calculation function
* allow the TS to be configured with either sigmas in a file, or calculation inputs
* send the calculated sigmas and expected noise ratio to the DCs and SKs
* add sanity checks for the expected noise ratio to the TS, DCs, and SKs
* make the unit tests work with automatic sigma calculation

**Comment by teor2345** [comment]
I have a working unit test that takes the stats parameters as inputs.
I still need to:
* commit working unit test to a github branch (in coherent stages)
* cast all inputs to float()
* write the TS, DC, and SK code
* allow the TS to dump the results to a file as soon as they are calculated, as well as at the end of the round
* create a file for input into the integration test

**Comment by teor2345** [comment]
The working data structure and unit tests are in:
https://github.com/teor2345/privcount/tree/auto-stats-v4

**Comment by teor2345** [comment]
This is ready for review in branch #115.
The input format and config are self-documenting via comments - I am happy to open another ticket to document them further, but I think I'd be repeating the comments in the config file.
